/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReleaseCalendarRouteImport } from './routes/release-calendar'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as GameIdRouteImport } from './routes/game.$id'
import { Route as GameListIdRouteImport } from './routes/game-list.$id'
import { Route as CompanyIdRouteImport } from './routes/company.$id'
import { Route as CollectionIdRouteImport } from './routes/collection.$id'
import { Route as ProfileIdFriendsRouteImport } from './routes/profile_.$id.friends'
import { Route as ProfileIdCollectionsRouteImport } from './routes/profile_.$id.collections'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleaseCalendarRoute = ReleaseCalendarRouteImport.update({
  id: '/release-calendar',
  path: '/release-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GameListIdRoute = GameListIdRouteImport.update({
  id: '/game-list/$id',
  path: '/game-list/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIdRoute = CompanyIdRouteImport.update({
  id: '/company/$id',
  path: '/company/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIdRoute = CollectionIdRouteImport.update({
  id: '/collection/$id',
  path: '/collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdFriendsRoute = ProfileIdFriendsRouteImport.update({
  id: '/profile_/$id/friends',
  path: '/profile/$id/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdCollectionsRoute = ProfileIdCollectionsRouteImport.update({
  id: '/profile_/$id/collections',
  path: '/profile/$id/collections',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/release-calendar': typeof ReleaseCalendarRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/collection/$id': typeof CollectionIdRoute
  '/company/$id': typeof CompanyIdRoute
  '/game-list/$id': typeof GameListIdRoute
  '/game/$id': typeof GameIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/$id/collections': typeof ProfileIdCollectionsRoute
  '/profile/$id/friends': typeof ProfileIdFriendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/release-calendar': typeof ReleaseCalendarRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/collection/$id': typeof CollectionIdRoute
  '/company/$id': typeof CompanyIdRoute
  '/game-list/$id': typeof GameListIdRoute
  '/game/$id': typeof GameIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/$id/collections': typeof ProfileIdCollectionsRoute
  '/profile/$id/friends': typeof ProfileIdFriendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/release-calendar': typeof ReleaseCalendarRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/collection/$id': typeof CollectionIdRoute
  '/company/$id': typeof CompanyIdRoute
  '/game-list/$id': typeof GameListIdRoute
  '/game/$id': typeof GameIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile_/$id/collections': typeof ProfileIdCollectionsRoute
  '/profile_/$id/friends': typeof ProfileIdFriendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/home'
    | '/login'
    | '/notifications'
    | '/register'
    | '/release-calendar'
    | '/search'
    | '/settings'
    | '/collection/$id'
    | '/company/$id'
    | '/game-list/$id'
    | '/game/$id'
    | '/profile/$id'
    | '/profile/$id/collections'
    | '/profile/$id/friends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/home'
    | '/login'
    | '/notifications'
    | '/register'
    | '/release-calendar'
    | '/search'
    | '/settings'
    | '/collection/$id'
    | '/company/$id'
    | '/game-list/$id'
    | '/game/$id'
    | '/profile/$id'
    | '/profile/$id/collections'
    | '/profile/$id/friends'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/home'
    | '/login'
    | '/notifications'
    | '/register'
    | '/release-calendar'
    | '/search'
    | '/settings'
    | '/collection/$id'
    | '/company/$id'
    | '/game-list/$id'
    | '/game/$id'
    | '/profile/$id'
    | '/profile_/$id/collections'
    | '/profile_/$id/friends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  ReleaseCalendarRoute: typeof ReleaseCalendarRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  CollectionIdRoute: typeof CollectionIdRoute
  CompanyIdRoute: typeof CompanyIdRoute
  GameListIdRoute: typeof GameListIdRoute
  GameIdRoute: typeof GameIdRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ProfileIdCollectionsRoute: typeof ProfileIdCollectionsRoute
  ProfileIdFriendsRoute: typeof ProfileIdFriendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release-calendar': {
      id: '/release-calendar'
      path: '/release-calendar'
      fullPath: '/release-calendar'
      preLoaderRoute: typeof ReleaseCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-list/$id': {
      id: '/game-list/$id'
      path: '/game-list/$id'
      fullPath: '/game-list/$id'
      preLoaderRoute: typeof GameListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$id': {
      id: '/company/$id'
      path: '/company/$id'
      fullPath: '/company/$id'
      preLoaderRoute: typeof CompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$id': {
      id: '/collection/$id'
      path: '/collection/$id'
      fullPath: '/collection/$id'
      preLoaderRoute: typeof CollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/$id/friends': {
      id: '/profile_/$id/friends'
      path: '/profile/$id/friends'
      fullPath: '/profile/$id/friends'
      preLoaderRoute: typeof ProfileIdFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/$id/collections': {
      id: '/profile_/$id/collections'
      path: '/profile/$id/collections'
      fullPath: '/profile/$id/collections'
      preLoaderRoute: typeof ProfileIdCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  ReleaseCalendarRoute: ReleaseCalendarRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  CollectionIdRoute: CollectionIdRoute,
  CompanyIdRoute: CompanyIdRoute,
  GameListIdRoute: GameListIdRoute,
  GameIdRoute: GameIdRoute,
  ProfileIdRoute: ProfileIdRoute,
  ProfileIdCollectionsRoute: ProfileIdCollectionsRoute,
  ProfileIdFriendsRoute: ProfileIdFriendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
